export const achievements = [
  { id: 1, title: 'First Book', icon: '📖', description: 'Finish your first book.', unlocked: true },
  { id: 2, title: 'Speed Reader', icon: '⚡', description: 'Finish a book in one day.', unlocked: true },
  { id: 3, title: 'Bookworm', icon: '🐛', description: 'Read for 7 consecutive days.', unlocked: true },
  { id: 4, title: 'Genre Explorer', icon: '🗺️', description: 'Read books from 5 different genres.', unlocked: true },
  { id: 5, title: 'Marathon Reader', icon: '🏃', description: 'Complete a book over 500 pages.', unlocked: true },
  { id: 6, title: 'Night Owl', icon: '🦉', description: 'Log a reading session after midnight.', unlocked: true },
  { id: 7, title: 'Page Turner', icon: '📄', description: 'Read 1000 pages in total.', unlocked: true },
  { id: 8, title: 'Weekend Warrior', icon: '🛋️', description: 'Read on both Saturday and Sunday.', unlocked: true },
  { id: 9, title: 'Goal Getter', icon: '🎯', description: 'Achieve a weekly reading goal.', unlocked: true },
  { id: 10, title: 'Commentator', icon: '💬', description: 'Comment on 3 books.', unlocked: false },
  { id: 11, title: 'Social Reader', icon: '👥', description: 'Add 3 friends to your network.', unlocked: false },
  { id: 12, title: 'Streak Master', icon: '🔥', description: 'Maintain a 30-day reading streak.', unlocked: false },
  { id: 13, title: 'ISBN Hunter', icon: '🔍', description: 'Scan 5 books using ISBN.', unlocked: false },
  { id: 14, title: 'Early Bird', icon: '🌅', description: 'Log a reading session before 7 AM.', unlocked: false },
  { id: 15, title: 'Library Builder', icon: '🏗️', description: 'Add 20 books to your library.', unlocked: false },
  { id: 16, title: 'Daily Devotee', icon: '🗓️', description: 'Read every day for an entire week.', unlocked: false },
  { id: 17, title: 'Fast Five', icon: '🚀', description: 'Finish 5 books within a month.', unlocked: false },
  { id: 18, title: 'Comeback Kid', icon: '🔁', description: 'Resume reading after 7+ days of inactivity.', unlocked: false },
  { id: 19, title: 'Tag Collector', icon: '🏷️', description: 'Read books from 10 different tags/keywords.', unlocked: false },
  { id: 20, title: 'Feedback Fanatic', icon: '📝', description: 'Rate or review 10 books.', unlocked: false },
];
